/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as OpportunitiesRouteImport } from './routes/opportunities'
import { Route as GemologistRouteImport } from './routes/gemologist'
import { Route as CurrentStateRouteImport } from './routes/current-state'
import { Route as CopilotRouteImport } from './routes/copilot'
import { Route as ApiTtsRouteImport } from './routes/api.tts'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunitiesRoute = OpportunitiesRouteImport.update({
  id: '/opportunities',
  path: '/opportunities',
  getParentRoute: () => rootRouteImport,
} as any)
const GemologistRoute = GemologistRouteImport.update({
  id: '/gemologist',
  path: '/gemologist',
  getParentRoute: () => rootRouteImport,
} as any)
const CurrentStateRoute = CurrentStateRouteImport.update({
  id: '/current-state',
  path: '/current-state',
  getParentRoute: () => rootRouteImport,
} as any)
const CopilotRoute = CopilotRouteImport.update({
  id: '/copilot',
  path: '/copilot',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTtsRoute = ApiTtsRouteImport.update({
  id: '/api/tts',
  path: '/api/tts',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/copilot': typeof CopilotRoute
  '/current-state': typeof CurrentStateRoute
  '/gemologist': typeof GemologistRoute
  '/opportunities': typeof OpportunitiesRoute
  '/profile': typeof ProfileRoute
  '/api/tts': typeof ApiTtsRoute
}
export interface FileRoutesByTo {
  '/copilot': typeof CopilotRoute
  '/current-state': typeof CurrentStateRoute
  '/gemologist': typeof GemologistRoute
  '/opportunities': typeof OpportunitiesRoute
  '/profile': typeof ProfileRoute
  '/api/tts': typeof ApiTtsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/copilot': typeof CopilotRoute
  '/current-state': typeof CurrentStateRoute
  '/gemologist': typeof GemologistRoute
  '/opportunities': typeof OpportunitiesRoute
  '/profile': typeof ProfileRoute
  '/api/tts': typeof ApiTtsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/copilot'
    | '/current-state'
    | '/gemologist'
    | '/opportunities'
    | '/profile'
    | '/api/tts'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/copilot'
    | '/current-state'
    | '/gemologist'
    | '/opportunities'
    | '/profile'
    | '/api/tts'
  id:
    | '__root__'
    | '/copilot'
    | '/current-state'
    | '/gemologist'
    | '/opportunities'
    | '/profile'
    | '/api/tts'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  CopilotRoute: typeof CopilotRoute
  CurrentStateRoute: typeof CurrentStateRoute
  GemologistRoute: typeof GemologistRoute
  OpportunitiesRoute: typeof OpportunitiesRoute
  ProfileRoute: typeof ProfileRoute
  ApiTtsRoute: typeof ApiTtsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunities': {
      id: '/opportunities'
      path: '/opportunities'
      fullPath: '/opportunities'
      preLoaderRoute: typeof OpportunitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gemologist': {
      id: '/gemologist'
      path: '/gemologist'
      fullPath: '/gemologist'
      preLoaderRoute: typeof GemologistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/current-state': {
      id: '/current-state'
      path: '/current-state'
      fullPath: '/current-state'
      preLoaderRoute: typeof CurrentStateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/copilot': {
      id: '/copilot'
      path: '/copilot'
      fullPath: '/copilot'
      preLoaderRoute: typeof CopilotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tts': {
      id: '/api/tts'
      path: '/api/tts'
      fullPath: '/api/tts'
      preLoaderRoute: typeof ApiTtsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  CopilotRoute: CopilotRoute,
  CurrentStateRoute: CurrentStateRoute,
  GemologistRoute: GemologistRoute,
  OpportunitiesRoute: OpportunitiesRoute,
  ProfileRoute: ProfileRoute,
  ApiTtsRoute: ApiTtsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
